export * from './actuator.service';
import { ActuatorService } from './actuator.service';
export * from './deleteUserController.service';
import { DeleteUserControllerService } from './deleteUserController.service';
export * from './getAllUsersController.service';
import { GetAllUsersControllerService } from './getAllUsersController.service';
export * from './registerNewUserController.service';
import { RegisterNewUserControllerService } from './registerNewUserController.service';
export * from './updateUserController.service';
import { UpdateUserControllerService } from './updateUserController.service';
export const APIS = [ActuatorService, DeleteUserControllerService, GetAllUsersControllerService, RegisterNewUserControllerService, UpdateUserControllerService];
